#!/usr/bin/env bash
# render-workspace-agent-map.sh
#
# Regenerate wezterm-x/local/workspace-agent-map.tsv from the same
# workspaces.lua merge WezTerm uses (public baseline ∪ local override).
# Shell launch paths (Alt+g, Ctrl+k g, refresh, cold-spawn) read this map
# via resume-command.sh so per-item `launcher` overrides apply beyond
# workspace first-open. See docs/workspaces.md.
#
# Output is under wezterm-x/local/ (gitignored) because it embeds private
# project paths. Re-run via wezterm-runtime-sync after editing
# wezterm-x/local/workspaces.lua.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RUNTIME_SOURCE="${WEZTERM_RUNTIME_SOURCE_DIR:-$REPO_ROOT/wezterm-x}"
OUT_DIR="$RUNTIME_SOURCE/local"
OUT="$OUT_DIR/workspace-agent-map.tsv"
DUMP_LUA="$SCRIPT_DIR/dump-workspace-agent-map.lua"
MOCK_PATH="$REPO_ROOT/tests/lua-units/?.lua"

if ! command -v lua5.4 >/dev/null 2>&1; then
  printf 'render-workspace-agent-map.sh: lua5.4 is required but not on PATH\n' >&2
  printf 'install with: sudo apt install lua5.4\n' >&2
  exit 1
fi

if [[ ! -f "$DUMP_LUA" ]]; then
  printf 'render-workspace-agent-map.sh: dump script missing at %s\n' "$DUMP_LUA" >&2
  exit 1
fi

if [[ ! -f "$RUNTIME_SOURCE/workspaces.lua" ]]; then
  printf 'render-workspace-agent-map.sh: workspaces.lua missing at %s\n' \
    "$RUNTIME_SOURCE/workspaces.lua" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# Build a throwaway runtime tree so:
#   1. local/workspaces.lua (which resolves via wezterm.config_dir/.wezterm-x)
#      sees the same lua/ + local/ as the source tree
#   2. repo-worktree-task.env can be injected without writing into source
tmp_config="$(mktemp -d "${TMPDIR:-/tmp}/workspace-agent-map.XXXXXX")"
cleanup() {
  rm -rf "$tmp_config"
}
trap cleanup EXIT

runtime_link="$tmp_config/.wezterm-x"
mkdir -p "$runtime_link"
ln -s "$RUNTIME_SOURCE/lua" "$runtime_link/lua"
ln -s "$RUNTIME_SOURCE/local" "$runtime_link/local"
ln -s "$RUNTIME_SOURCE/workspaces.lua" "$runtime_link/workspaces.lua"
# Optional metadata that constants.lua may read
for optional in repo-root.txt main-repo-root.txt; do
  if [[ -e "$RUNTIME_SOURCE/$optional" ]]; then
    ln -s "$RUNTIME_SOURCE/$optional" "$runtime_link/$optional"
  fi
done

if [[ -f "$RUNTIME_SOURCE/repo-worktree-task.env" ]]; then
  ln -s "$RUNTIME_SOURCE/repo-worktree-task.env" "$runtime_link/repo-worktree-task.env"
elif [[ -f "$REPO_ROOT/config/worktree-task.env" ]]; then
  cp -p "$REPO_ROOT/config/worktree-task.env" "$runtime_link/repo-worktree-task.env"
fi

body="$(
  WEZTERM_CONFIG_REPO="$REPO_ROOT" \
  WEZTERM_RUNTIME_DIR="$runtime_link" \
  WORKSPACE_AGENT_MAP_CONFIG_DIR="$tmp_config" \
  WEZTERM_MOCK_PATH="$MOCK_PATH" \
    lua5.4 "$DUMP_LUA"
)" || {
  printf 'render-workspace-agent-map.sh: dump failed\n' >&2
  exit 1
}

{
  printf '# generated by render-workspace-agent-map.sh — do not edit\n'
  printf '# cwd\tprofile_base\n'
  if [[ -n "$body" ]]; then
    printf '%s\n' "$body"
  fi
} > "$OUT.tmp"

mv -f "$OUT.tmp" "$OUT"
row_count=0
if [[ -n "$body" ]]; then
  row_count="$(printf '%s\n' "$body" | grep -c .)"
fi
printf 'render-workspace-agent-map.sh: wrote %s (%s rows)\n' "$OUT" "$row_count"
