#!/usr/bin/env bash
# render-tmux-appearance.sh
#
# Emit the tmux pane/status background lines for the active appearance preset.
# The preset name is the single source of truth (WEZTERM_APPEARANCE_PRESET in
# wezterm-x/local/shared.env); the WezTerm side of the same preset lives in
# wezterm-x/lua/config/appearance-presets.lua. Keep the two in lockstep.
#
# Output: wezterm-x/tmux/appearance.generated.conf (gitignored). tmux.conf
# loads it via `source-file -Fq`, so running wezterm-runtime-sync between
# preset changes is what makes them visible to tmux.
#
# Presets:
#   opaque  (default) — original solid look: dim cream inactive panes, cream
#                       active pane + status bar.
#   frosted           — every pane + the status bar use bg=default so they
#                       inherit WezTerm's window transparency / acrylic.
#
# Full model + rationale: docs/appearance-presets.md.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SHARED_ENV="$REPO_ROOT/wezterm-x/local/shared.env"
OUT_DIR="$REPO_ROOT/wezterm-x/tmux"
OUT="$OUT_DIR/appearance.generated.conf"

preset='opaque'
if [[ -f "$SHARED_ENV" ]]; then
  # Grab the last WEZTERM_APPEARANCE_PRESET assignment, strip quotes/space.
  val="$(sed -n "s/^[[:space:]]*WEZTERM_APPEARANCE_PRESET[[:space:]]*=[[:space:]]*//p" "$SHARED_ENV" \
    | tail -n1 | tr -d "\"' " )"
  [[ -n "$val" ]] && preset="$val"
fi

case "$preset" in
  frosted)
    status_bg='default'; window_bg='default'; active_bg='default' ;;
  opaque)
    status_bg='#f1f0e9'; window_bg='#eae9e1'; active_bg='#f1f0e9' ;;
  *)
    printf 'render-tmux-appearance.sh: unknown preset %q, falling back to opaque\n' "$preset" >&2
    preset='opaque'; status_bg='#f1f0e9'; window_bg='#eae9e1'; active_bg='#f1f0e9' ;;
esac

# Popups always use a solid cream fill, even under the frosted preset.
# Transparent popup cells let the underlying pane (often streaming
# CJK agent scrollback) show through empty areas of the overlay and
# read as mojibake when combined with copy-mode auto-refresh.
popup_bg='#f1f0e9'
popup_fg='#393a34'
popup_border_fg='#8c6c3e'

mkdir -p "$OUT_DIR"
tmp_out="$OUT.tmp.$$"
{
  printf '# Generated by scripts/runtime/render-tmux-appearance.sh — do not edit.\n'
  printf '# Appearance preset: %s (WEZTERM_APPEARANCE_PRESET in local/shared.env).\n' "$preset"
  printf 'set -g status-style "bg=%s,fg=#393a34"\n' "$status_bg"
  printf 'set -g window-style "fg=default,bg=%s"\n' "$window_bg"
  printf 'set -g window-active-style "fg=default,bg=%s"\n' "$active_bg"
  printf 'set -g popup-style "bg=%s,fg=%s"\n' "$popup_bg" "$popup_fg"
  printf 'set -g popup-border-style "fg=%s,bg=%s"\n' "$popup_border_fg" "$popup_bg"
} > "$tmp_out"

# Only replace OUT (and bump its mtime) when content actually changed —
# same skip-if-current contract as render-tmux-bindings.sh.
if [[ -f "$OUT" ]] && cmp -s "$tmp_out" "$OUT"; then
  rm -f "$tmp_out"
  printf 'render-tmux-appearance.sh: up-to-date %s (preset=%s)\n' "$OUT" "$preset"
else
  mv -f "$tmp_out" "$OUT"
  printf 'render-tmux-appearance.sh: wrote %s (preset=%s)\n' "$OUT" "$preset"
fi
