#!/usr/bin/env bash
# Patch generated OpenClaw ACP wrappers so C3 backends never write the
# interactive WezDeck attention badge.
#
# Wrappers live in ~/.openclaw/acpx/ and are regenerated by @openclaw/acpx —
# re-run this after OpenClaw/acpx updates.
#
# Usage:
#   openclaw/scripts/patch-acpx-attention-skip.sh
#   openclaw/scripts/patch-acpx-attention-skip.sh --check
set -euo pipefail

check_only=0
[[ "${1:-}" == "--check" ]] && check_only=1

acpx_dir="${OPENCLAW_ACPX_DIR:-$HOME/.openclaw/acpx}"
marker="wezdeck: attention-skip"

patch_one() {
  local file=$1
  [[ -f "$file" ]] || { echo "missing: $file" >&2; return 1; }

  if grep -q "$marker" "$file"; then
    echo "ok (already patched): $file"
    return 0
  fi

  if ((check_only)); then
    echo "NEED PATCH: $file" >&2
    return 2
  fi

  python3 - "$file" "$marker" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
marker = sys.argv[2]
text = path.read_text(encoding="utf-8")
if marker in text:
    print(f"ok (already patched): {path}")
    raise SystemExit(0)

needle_claude = "const env = {\n  ...process.env,\n};"
needle_codex = "const env = {\n  ...process.env,\n  CODEX_HOME: codexHome,\n};"

inject_claude = f"""const env = {{
  ...process.env,
  // {marker} — do not decorate WezDeck interactive attention
  AGENT_ATTENTION_SKIP: "1",
  WEZTERM_ATTENTION_SKIP: "1",
  OPENCLAW_ACP: "1",
}};
delete env.WEZTERM_PANE;
delete env.WEZTERM_UNIX_SOCKET;
delete env.TMUX;
delete env.TMUX_PANE;"""

inject_codex = f"""const env = {{
  ...process.env,
  CODEX_HOME: codexHome,
  // {marker} — do not decorate WezDeck interactive attention
  AGENT_ATTENTION_SKIP: "1",
  WEZTERM_ATTENTION_SKIP: "1",
  OPENCLAW_ACP: "1",
}};
delete env.WEZTERM_PANE;
delete env.WEZTERM_UNIX_SOCKET;
delete env.TMUX;
delete env.TMUX_PANE;"""

if needle_codex in text:
    text2 = text.replace(needle_codex, inject_codex, 1)
elif needle_claude in text:
    text2 = text.replace(needle_claude, inject_claude, 1)
else:
    print(f"error: env block not found in {path}", file=sys.stderr)
    raise SystemExit(1)

if text2 == text:
    print(f"error: no change applied to {path}", file=sys.stderr)
    raise SystemExit(1)

path.write_text(text2, encoding="utf-8")
print(f"patched: {path}")
PY
}

rc=0
for name in claude-agent-acp-wrapper.mjs codex-acp-wrapper.mjs; do
  set +e
  patch_one "$acpx_dir/$name"
  st=$?
  set -e
  if ((st != 0)); then
    rc=$st
  fi
done
exit "$rc"
