export WEZTERM_RUNTIME_LOG_ENABLED=0
export WEZTERM_RUNTIME_LOG_LEVEL=info
export WEZTERM_RUNTIME_LOG_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/wezterm-runtime.log"
export WEZTERM_RUNTIME_LOG_CATEGORIES=""
